---
.dynamic_pipeline_rules:
  rules:
    - if: >
        $DYNAMIC_PIPELINE == "True"
        && $CI_PIPELINE_SOURCE == "api"
      when: on_success
    - when: never

Generate pipeline:
 stage: prepare
 extends: dynamic_pipeline_rules
 script: python ./generate_pipeline.py
 artifacts:
  paths:
    - temp/dynamic-pipeline.yml
  expire_in: "1 days"

Child pipeline:
 stage: trigger
 extends: dynamic_pipeline_rules
 trigger:
  include:
    - artifact: temp/dynamic-pipeline.yml
      job: Generate pipeline
  strategy: depend
...