name: Build jobs

on:
  workflow_call:

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        job_name: ['linux', 'windows']
        include:
          - job_name: linux
            os: ubuntu-latest
            shell: bash {0}
          - job_name: windows
            os: windows-latest
            shell: bash {0}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    name: cicd-tool-${{ matrix.job_name }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: |
          pyinstaller main.py --noconsole --icon=images/tool_logo.png --distpath dist-${{ matrix.job_name }}
          mkdir dist-${{ matrix.job_name }}/main/configs
          mkdir dist-${{ matrix.job_name }}/main/logs
          cp tool.yml dist-${{ matrix.job_name }}/main/configs
          cp -r images dist-${{ matrix.job_name }}/main/images
      - uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          compression-level: 0
          name: cicd-tool-${{ matrix.job_name }}
          path: dist-${{ matrix.job_name }}/main
